server:
  context-path: /auth
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopAuth
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true