security:
  oauth2:
    client:
      clientId: category-service
      clientSecret: secret
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

server:
  context-path: /categories
  port: 4000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true