security:
  oauth2:
    client:
      clientId: category-service
      clientSecret: 123456
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials,password
      scope: server

server:
  servlet:
    context-path: /categories
  port: 4000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true