security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: product-service
      clientSecret: secret
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

server:
  context-path: /products
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true